### ISSUE TITLE
does not handle urls correctly

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [silverwind/file-extension#1]
http://google.com/some/path/guy.zip?hello=world#foo=bar

will return 

zip?hello=world#foo=bar

which is incorrect. 

you can use `filename = require('url').parse(filename).pathname` to easily strip everything from url but the path (/some/path/guy.zip)

**Comment by silverwind** [comment]
I'd say this is working as intended. You're not supposed to feed URLs directly into this module, only file system paths. In your case, you could first test for an URL, like `/.+:\/\/.+/.test(string)` and if it matches, feed `url.pathname` to this module.
