### ISSUE TITLE
Feature Request: use basename for extension-less files

### ISSUE THREAD

**Issue by dominicbarnes** [silverwind/file-extension#3]
I've been using this library upstream in a project of my own, and I've run across an issue that I'm not sure if it should be handled down here in this library or further upstream.

Would it be possible for this library to also handle "extension-less" files? (eg: `Makefile`, `CNAME`, `Dockerfile`)

I would think that for a file without a `.`, the basename would be returned instead.

``` js
extension('Makefile')
// 'makefile'
```

Of course, `{ preserveCase: true }` can also remain as a feature:

``` js
extension('CNAME', { preserveCase: true })
// 'CNAME'
```

If that doesn't seem to belong here in this library, I totally understand and will handle it upstream instead. If you're interested, I'm more than willing to write a PR.

**Comment by dominicbarnes** [comment]
I also understand this would constitute a breaking change, since `extension('Makefile')` currently returns `''`.

An alternative to a breaking change would be to put this behavior behind it's own option:

``` js
extension('Makefile')
// ''

extension('Makefile', { basenameFallback: true })
// 'makefile'

extension('Makefile', { preserveCase: true, basenameFallback: true })
// 'Makefile'
```

**Comment by silverwind** [comment]
I think I'd be fine with a breaking change. It makes sense for extension-less files to return the full name.

**Comment by dominicbarnes** [comment]
All right, I will work on a PR for you to review. :smile:

**Comment by silverwind** [comment]
Please try if `/[^.]*$/.exec(filename)[0]` can satisfy all cases.

**Comment by silverwind** [comment]
Turns out the single regex was slightly faster, so I went with it. Released 3.0.0 with this change.

**Comment by dominicbarnes** [comment]
Wonderful! Thank you very much!

**Comment by silverwind** [comment]
And 3.0.1 is out. I totally forgot to support paths :)

**Comment by dominicbarnes** [comment]
Ah yeah, I was going to ask about that next, but it seemed like this library assumed you would use "basename" instead of a full path. (which is what I started using upstream)
